### ISSUE TITLE
Create more tutorials

### ISSUE THREAD

**Issue by JaDogg** [YakshaLang/Yaksha#27]

**Comment by kana800** [comment]
Do you need help with this?
I would be happy to write some tutorials and docs

**Comment by JaDogg** [comment]
Hey, @kana800 sure I would like some help with this. I'll comment here when I create a repo for that. I'm thinking of creating a new repo for this purpose.

**Comment by JaDogg** [comment]
Repo created --> https://github.com/YakshaLang/Tutorials

**Comment by kana800** [comment]
can you tell me what sort of tutorials you are looking for so i can build up on it !

**Comment by JaDogg** [comment]
Simple ones like installing plugin. Setting up PATH.

I have 2 in discussions tab in YakshaLang org we should move those 2 as
well.

ZIP file there can be put to the same repo or just add the code to a
markdown file.

Need to add links from README to other tutorials.

You might need to refer jekyll docs to see how that is done.

**Comment by JaDogg** [comment]
Figured out how to add links see the repo, :)

**Comment by kana800** [comment]
alrighty i will work on it on this weekend

**Comment by JaDogg** [comment]
Created a tutorial and moved it to main documentation repo.
