### ISSUE TITLE
ccode in module level assignment

### ISSUE THREAD

**Issue by ac2pic** [YakshaLang/Yaksha#46]
`a: Const[int] = ccode "abc"`
Shows up as 
`#define yy__a (abc)`
Is this a bug or intentional?

**Comment by JaDogg** [comment]
It is intentional to expose globals etc.

FYI - I'm inactive these days and may not respond as I'm sick.

**Comment by ac2pic** [comment]
Thank you for replying. Hope you feel better.

**Comment by JaDogg** [comment]
In any case I would avoid using `ccode` unless it is really required. :) (such as wrapping a C library)
