### ISSUE TITLE
README feedback

### ISSUE THREAD

**Issue by paddymul** [YakshaLang/Yaksha#72]
There is essentially no README.  Your README is the first chance to speak to potential users who land on your repo.

What is the aim of this language?
What problems does it solve?
What are the expected skills of developers (Should you know haskell and be dissapointed with it's type system? Maybe you want a more expressive react.)

---- 

After looking at the docs for the standard lib, this looks like a close to typed python that maps more closely to C

The libs docs doesn't link to the tutorial, forcing me to go back to the README

This link https://yakshalang.github.io/documentation should be the first link for your docs.  They are good.  I have a much better feel for the philosophy of the language after reading this

YAMA proposals is a 404 https://github.com/YakshaLang/YAMA/tree/main/proposals

On the demos:
https://github.com/YakshaLang/YAMA/tree/main/proposals
explain that fractal tree is Yakasha compiled to WASM running in the browser.  That's impressive.
https://yakshalang.github.io/static_demos/tree/wind_tree.html

Space blast looks fun,  by default it was sized too big for my 14 inch Mac Book.  Why don't you try a smaller default resolution.  It's still impressive at non full screen.

I would recommend using github issues.  It might not be your favorite, but it's more relatable to people looking to adopt your language.

-----

After reading through your docs how does this sound as a description of your language:

"Looks like python, compiles to C, then to WASM so it can run in the browser.  When you dig deeper there is an advanced lisp based macro language to help with zero cost meta programming."

----

There's a lot of good stuff here, talk about it and how it can be used.

**Comment by JaDogg** [comment]
Thank you very much to go through things for me. :) Will update the README. 👍🏽

**Comment by JaDogg** [comment]
- [x] Update README
- [x] Fix YAMA link
- [ ] Update space blast to be a smaller size
- [ ] Explain how the fractal tree is running in the browser

**Comment by JaDogg** [comment]
Thank you very much for review.
